title: Monit Sharma
logo: /assets/imgs/image.jpg
description: Hello there! I am Monit, a researcher passionate about quantum computing and its applications.
show_downloads: true
theme: jekyll-theme-minimal
social_links:
  - { platform: linkedin,user_url: "www.linkedin.com/in/monitsharma/" }
  - { platform: github,user_url: "github.com/monitsharma" }
  - { platform: twitter,user_url: "twitter.com/monitsharma" }
  - { platform: email,user_url: "mailto:monitsharma437@gmail.com" }
  - { platform: cv,user_url: "/assets/docs/CV_MonitSharma.pdf" }

